2022-03-14 16:20:54,445 INFO    MainThread:15544 [wandb_setup.py:_flush():71] setting env: {'start_method': 'thread'}
2022-03-14 16:20:54,445 INFO    MainThread:15544 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-14 16:20:54,445 INFO    MainThread:15544 [wandb_init.py:_log_setup():371] Logging user logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\logs\debug.log
2022-03-14 16:20:54,445 INFO    MainThread:15544 [wandb_init.py:_log_setup():372] Logging internal logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\logs\debug-internal.log
2022-03-14 16:20:54,445 INFO    MainThread:15544 [wandb_init.py:init():404] calling init triggers
2022-03-14 16:20:54,447 INFO    MainThread:15544 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'workers': 20, 'epochs': 2, 'batch_size': 64, 'learning_rate': 0.2, 'dropout': 0.01, 'weight_decay': 1e-06, 'clip': 1, 'betas': (0.9, 0.98), 'eps': 1e-09, 'loss_fn': 'cross_entropy', 'dmodel': 768, 'nhead': 3, 'dfeedforward': 256, 'nlayers': 3, 'tokenizer': 'bert-base-multilingual-cased', 'mbert_out_size': 768, 'checkpoint_dir': WindowsPath('checkpoint'), 'ngpus_per_node': 1, 'rank': 0, 'dist_url': 'tcp://localhost:58472', 'world_size': 1}
2022-03-14 16:20:54,447 INFO    MainThread:15544 [wandb_init.py:init():460] starting backend
2022-03-14 16:20:54,450 INFO    MainThread:15544 [backend.py:ensure_launched():216] starting backend process...
2022-03-14 16:20:54,451 INFO    MainThread:15544 [backend.py:ensure_launched():222] started backend process with pid: 0
2022-03-14 16:20:54,451 INFO    BackendThr:15544 [internal.py:wandb_internal():90] W&B internal server running at pid: 15544, started at: 2022-03-14 16:20:54.451183
2022-03-14 16:20:54,451 INFO    MainThread:15544 [wandb_init.py:init():469] backend started and connected
2022-03-14 16:20:54,454 INFO    MainThread:15544 [wandb_init.py:init():533] updated telemetry
2022-03-14 16:20:54,455 INFO    WriterThread:15544 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\run-23a3pmae.wandb
2022-03-14 16:20:54,504 INFO    MainThread:15544 [wandb_init.py:init():563] communicating current version
2022-03-14 16:20:54,754 INFO    MainThread:15544 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-14 16:20:54,756 INFO    MainThread:15544 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-14 16:20:55,124 INFO    MainThread:15544 [wandb_init.py:init():606] starting run threads in backend
2022-03-14 16:20:55,128 INFO    SenderThread:15544 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files
2022-03-14 16:20:55,128 INFO    SenderThread:15544 [sender.py:_start_run_threads():807] run started: 23a3pmae with start time 1647255054
2022-03-14 16:20:55,129 INFO    SenderThread:15544 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-14 16:20:56,130 INFO    Thread-17 :15544 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\requirements.txt
2022-03-14 16:20:56,131 INFO    Thread-17 :15544 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\conda-environment.yaml
2022-03-14 16:20:56,131 INFO    Thread-17 :15544 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\wandb-summary.json
2022-03-14 16:20:57,416 INFO    SenderThread:15544 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-14 16:20:57,433 INFO    MainThread:15544 [wandb_run.py:_console_start():1810] atexit reg
2022-03-14 16:20:57,438 INFO    MainThread:15544 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-14 16:20:57,438 INFO    MainThread:15544 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-14 16:20:57,440 INFO    MainThread:15544 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-14 16:20:57,440 INFO    MainThread:15544 [wandb_init.py:init():633] run started, returning control to user process
2022-03-14 16:20:58,136 INFO    Thread-17 :15544 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\conda-environment.yaml
2022-03-14 16:20:58,136 INFO    Thread-17 :15544 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\wandb-metadata.json
2022-03-14 16:20:58,136 INFO    Thread-17 :15544 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\output.log
2022-03-14 16:20:58,624 INFO    Thread-24 :15544 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmp07wf26mqwandb\2z00qkge-wandb-metadata.json
2022-03-14 16:21:00,151 INFO    Thread-17 :15544 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\output.log
2022-03-14 16:21:02,164 INFO    Thread-17 :15544 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\output.log
2022-03-14 16:23:10,547 WARNING MsgRouterThr:15544 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-14 16:23:10,548 INFO    MainThread:15544 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-03-14 16:23:10,549 INFO    MainThread:15544 [wandb_run.py:_restore():1752] restore
2022-03-14 16:23:11,484 INFO    SenderThread:15544 [sender.py:finish():1070] shutting down sender
2022-03-14 16:23:11,484 INFO    WriterThread:15544 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\run-23a3pmae.wandb
2022-03-14 16:23:11,484 INFO    SenderThread:15544 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-14 16:23:12,104 INFO    SenderThread:15544 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\output.log
2022-03-14 16:23:12,104 INFO    SenderThread:15544 [dir_watcher.py:finish():313] scan: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files
2022-03-14 16:23:12,105 INFO    SenderThread:15544 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\conda-environment.yaml conda-environment.yaml
2022-03-14 16:23:12,105 INFO    SenderThread:15544 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\config.yaml config.yaml
2022-03-14 16:23:12,106 INFO    SenderThread:15544 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\output.log output.log
2022-03-14 16:23:12,114 INFO    SenderThread:15544 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\requirements.txt requirements.txt
2022-03-14 16:23:12,115 INFO    SenderThread:15544 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\wandb-metadata.json wandb-metadata.json
2022-03-14 16:23:12,118 INFO    SenderThread:15544 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\wandb-summary.json wandb-summary.json
2022-03-14 16:23:12,123 INFO    SenderThread:15544 [file_pusher.py:finish():177] shutting down file pusher
2022-03-14 16:23:12,123 INFO    SenderThread:15544 [file_pusher.py:join():182] waiting for file pusher
2022-03-14 16:23:12,993 INFO    Thread-32 :15544 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\requirements.txt
2022-03-14 16:23:13,001 INFO    Thread-31 :15544 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\output.log
2022-03-14 16:23:13,013 INFO    Thread-33 :15544 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\wandb-summary.json
2022-03-14 16:23:13,097 INFO    Thread-29 :15544 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\conda-environment.yaml
2022-03-14 16:23:13,127 INFO    Thread-30 :15544 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_162054-23a3pmae\files\config.yaml
2022-03-14 16:23:14,103 ERROR   BackendThr:15544 [internal.py:wandb_internal():158] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 99, in _run
    record = self._input_record_q.get(timeout=1)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
2022-03-14 16:23:16,198 INFO    MainThread:15544 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-03-14 16:23:16,307 INFO    MainThread:15544 [wandb_run.py:_restore():1752] restore
2022-03-14 16:23:16,332 INFO    MainThread:15544 [internal.py:handle_exit():77] Internal process exited
