2022-03-15 01:15:43,222 INFO    MainThread:21008 [wandb_setup.py:_flush():71] setting env: {'start_method': 'thread'}
2022-03-15 01:15:43,222 INFO    MainThread:21008 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-15 01:15:43,222 INFO    MainThread:21008 [wandb_init.py:_log_setup():371] Logging user logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\logs\debug.log
2022-03-15 01:15:43,223 INFO    MainThread:21008 [wandb_init.py:_log_setup():372] Logging internal logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\logs\debug-internal.log
2022-03-15 01:15:43,223 INFO    MainThread:21008 [wandb_init.py:init():404] calling init triggers
2022-03-15 01:15:43,237 INFO    MainThread:21008 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'workers': 20, 'epochs': 2, 'batch_size': 64, 'learning_rate': 0.2, 'dropout': 0.01, 'weight_decay': 1e-06, 'clip': 1, 'betas': (0.9, 0.98), 'eps': 1e-09, 'loss_fn': 'cross_entropy', 'dmodel': 768, 'nhead': 3, 'dfeedforward': 256, 'nlayers': 3, 'tokenizer': 'bert-base-multilingual-cased', 'mbert_out_size': 768, 'checkpoint_dir': WindowsPath('checkpoint'), 'ngpus_per_node': 1, 'rank': 0, 'dist_url': 'tcp://localhost:58472', 'world_size': 1}
2022-03-15 01:15:43,237 INFO    MainThread:21008 [wandb_init.py:init():460] starting backend
2022-03-15 01:15:43,242 INFO    MainThread:21008 [backend.py:ensure_launched():216] starting backend process...
2022-03-15 01:15:43,243 INFO    MainThread:21008 [backend.py:ensure_launched():222] started backend process with pid: 0
2022-03-15 01:15:43,243 INFO    BackendThr:21008 [internal.py:wandb_internal():90] W&B internal server running at pid: 21008, started at: 2022-03-15 01:15:43.243778
2022-03-15 01:15:43,244 INFO    MainThread:21008 [wandb_init.py:init():469] backend started and connected
2022-03-15 01:15:43,247 INFO    MainThread:21008 [wandb_init.py:init():533] updated telemetry
2022-03-15 01:15:43,249 INFO    WriterThread:21008 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\run-2h41rm9i.wandb
2022-03-15 01:15:43,298 INFO    MainThread:21008 [wandb_init.py:init():563] communicating current version
2022-03-15 01:15:43,692 INFO    MainThread:21008 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-15 01:15:43,694 INFO    MainThread:21008 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-15 01:15:44,205 INFO    MainThread:21008 [wandb_init.py:init():606] starting run threads in backend
2022-03-15 01:15:44,208 INFO    SenderThread:21008 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files
2022-03-15 01:15:44,208 INFO    SenderThread:21008 [sender.py:_start_run_threads():807] run started: 2h41rm9i with start time 1647287143
2022-03-15 01:15:44,209 INFO    SenderThread:21008 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-15 01:15:45,224 INFO    Thread-17 :21008 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\wandb-summary.json
2022-03-15 01:15:45,225 INFO    Thread-17 :21008 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\requirements.txt
2022-03-15 01:15:45,225 INFO    Thread-17 :21008 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\conda-environment.yaml
2022-03-15 01:15:46,493 INFO    SenderThread:21008 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-15 01:15:46,508 INFO    MainThread:21008 [wandb_run.py:_console_start():1810] atexit reg
2022-03-15 01:15:46,525 INFO    MainThread:21008 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-15 01:15:46,525 INFO    MainThread:21008 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-15 01:15:46,528 INFO    MainThread:21008 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-15 01:15:46,528 INFO    MainThread:21008 [wandb_init.py:init():633] run started, returning control to user process
2022-03-15 01:15:47,233 INFO    Thread-17 :21008 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\conda-environment.yaml
2022-03-15 01:15:47,233 INFO    Thread-17 :21008 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\output.log
2022-03-15 01:15:47,233 INFO    Thread-17 :21008 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\wandb-metadata.json
2022-03-15 01:15:47,799 INFO    Thread-24 :21008 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmpz46gxeg0wandb\g0dyod9c-wandb-metadata.json
2022-03-15 01:15:49,239 INFO    Thread-17 :21008 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\output.log
2022-03-15 01:22:22,066 INFO    SenderThread:21008 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-15 01:22:22,500 INFO    Thread-17 :21008 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\wandb-summary.json
2022-03-15 01:22:23,322 INFO    MainThread:21008 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-15 01:22:23,322 WARNING MsgRouterThr:21008 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-15 01:22:23,346 INFO    MainThread:21008 [wandb_run.py:_restore():1752] restore
2022-03-15 01:22:24,078 INFO    SenderThread:21008 [sender.py:finish():1070] shutting down sender
2022-03-15 01:22:24,078 INFO    WriterThread:21008 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\run-2h41rm9i.wandb
2022-03-15 01:22:24,078 INFO    SenderThread:21008 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-15 01:22:24,513 INFO    SenderThread:21008 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\output.log
2022-03-15 01:22:24,513 INFO    SenderThread:21008 [dir_watcher.py:finish():313] scan: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files
2022-03-15 01:22:24,514 INFO    SenderThread:21008 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\conda-environment.yaml conda-environment.yaml
2022-03-15 01:22:24,514 INFO    SenderThread:21008 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\config.yaml config.yaml
2022-03-15 01:22:24,515 INFO    SenderThread:21008 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\output.log output.log
2022-03-15 01:22:24,521 INFO    SenderThread:21008 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\requirements.txt requirements.txt
2022-03-15 01:22:24,530 INFO    SenderThread:21008 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\wandb-metadata.json wandb-metadata.json
2022-03-15 01:22:24,530 INFO    SenderThread:21008 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\wandb-summary.json wandb-summary.json
2022-03-15 01:22:24,533 INFO    SenderThread:21008 [file_pusher.py:finish():177] shutting down file pusher
2022-03-15 01:22:24,534 INFO    SenderThread:21008 [file_pusher.py:join():182] waiting for file pusher
2022-03-15 01:22:25,689 INFO    Thread-33 :21008 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\requirements.txt
2022-03-15 01:22:25,725 INFO    Thread-31 :21008 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\config.yaml
2022-03-15 01:22:25,728 INFO    Thread-34 :21008 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\wandb-summary.json
2022-03-15 01:22:25,733 INFO    Thread-32 :21008 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\output.log
2022-03-15 01:22:25,769 INFO    Thread-30 :21008 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_011543-2h41rm9i\files\conda-environment.yaml
2022-03-15 01:22:27,331 ERROR   BackendThr:21008 [internal.py:wandb_internal():158] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 99, in _run
    record = self._input_record_q.get(timeout=1)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
2022-03-15 01:22:28,928 INFO    MainThread:21008 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-03-15 01:22:34,041 INFO    MainThread:21008 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-03-15 01:22:34,149 INFO    MainThread:21008 [wandb_run.py:_restore():1752] restore
2022-03-15 01:22:34,177 INFO    MainThread:21008 [internal.py:handle_exit():77] Internal process exited
