2022-03-14 15:13:05,665 INFO    BackendThr:15796 [internal.py:wandb_internal():90] W&B internal server running at pid: 15796, started at: 2022-03-14 15:13:05.665045
2022-03-14 15:13:05,666 INFO    MainThread:15796 [wandb_init.py:init():469] backend started and connected
2022-03-14 15:13:05,667 DEBUG   MainThread:15796 [config_util.py:dict_from_config_file():102] no default config file found in config-defaults.yaml
2022-03-14 15:13:05,668 INFO    MainThread:15796 [wandb_init.py:init():533] updated telemetry
2022-03-14 15:13:05,669 INFO    WriterThread:15796 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\run-2w3zwz8t.wandb
2022-03-14 15:13:05,671 DEBUG   SenderThread:15796 [sender.py:send():234] send: header
2022-03-14 15:13:05,716 INFO    MainThread:15796 [wandb_init.py:init():563] communicating current version
2022-03-14 15:13:05,717 DEBUG   HandlerThread:15796 [handler.py:handle_request():130] handle_request: check_version
2022-03-14 15:13:05,717 DEBUG   SenderThread:15796 [sender.py:send_request():248] send_request: check_version
2022-03-14 15:13:05,971 INFO    MainThread:15796 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-14 15:13:05,974 INFO    MainThread:15796 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-14 15:13:05,975 DEBUG   SenderThread:15796 [sender.py:send():234] send: run
2022-03-14 15:13:06,429 INFO    MainThread:15796 [wandb_init.py:init():606] starting run threads in backend
2022-03-14 15:13:06,430 DEBUG   HandlerThread:15796 [handler.py:handle_request():130] handle_request: run_start
2022-03-14 15:13:06,431 INFO    SenderThread:15796 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files
2022-03-14 15:13:06,431 INFO    SenderThread:15796 [sender.py:_start_run_threads():807] run started: 2w3zwz8t with start time 1647250985
2022-03-14 15:13:06,432 DEBUG   SenderThread:15796 [sender.py:send():234] send: summary
2022-03-14 15:13:06,432 INFO    SenderThread:15796 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-14 15:13:06,445 DEBUG   HandlerThread:15796 [meta.py:__init__():40] meta init
2022-03-14 15:13:06,446 DEBUG   HandlerThread:15796 [meta.py:__init__():54] meta init done
2022-03-14 15:13:06,446 DEBUG   HandlerThread:15796 [meta.py:probe():214] probe
2022-03-14 15:13:06,458 DEBUG   HandlerThread:15796 [meta.py:_setup_git():204] setup git
2022-03-14 15:13:06,563 DEBUG   HandlerThread:15796 [meta.py:_setup_git():211] setup git done
2022-03-14 15:13:06,564 DEBUG   HandlerThread:15796 [meta.py:_save_pip():58] save pip
2022-03-14 15:13:06,564 DEBUG   HandlerThread:15796 [meta.py:_save_pip():72] save pip done
2022-03-14 15:13:06,564 DEBUG   HandlerThread:15796 [meta.py:_save_conda():79] save conda
2022-03-14 15:13:07,434 INFO    Thread-17 :15796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\conda-environment.yaml
2022-03-14 15:13:07,435 INFO    Thread-17 :15796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\wandb-summary.json
2022-03-14 15:13:07,435 INFO    Thread-17 :15796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\requirements.txt
2022-03-14 15:13:08,689 DEBUG   HandlerThread:15796 [meta.py:_save_conda():89] save conda done
2022-03-14 15:13:08,689 DEBUG   HandlerThread:15796 [meta.py:probe():252] probe done
2022-03-14 15:13:08,693 DEBUG   SenderThread:15796 [sender.py:send():234] send: files
2022-03-14 15:13:08,694 INFO    SenderThread:15796 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-14 15:13:08,715 DEBUG   HandlerThread:15796 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:13:08,715 DEBUG   SenderThread:15796 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:13:08,715 INFO    MainThread:15796 [wandb_run.py:_console_start():1810] atexit reg
2022-03-14 15:13:08,720 INFO    MainThread:15796 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-14 15:13:08,720 INFO    MainThread:15796 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-14 15:13:08,722 INFO    MainThread:15796 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-14 15:13:08,722 INFO    MainThread:15796 [wandb_init.py:init():633] run started, returning control to user process
2022-03-14 15:13:09,440 INFO    Thread-17 :15796 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\conda-environment.yaml
2022-03-14 15:13:09,441 INFO    Thread-17 :15796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\output.log
2022-03-14 15:13:09,441 INFO    Thread-17 :15796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\wandb-metadata.json
2022-03-14 15:13:09,796 INFO    Thread-22 :15796 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmpcc7_5oj0wandb\2pp5sh7x-wandb-metadata.json
2022-03-14 15:13:11,459 INFO    Thread-17 :15796 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\output.log
2022-03-14 15:13:12,688 INFO    MainThread:15796 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-14 15:13:12,689 WARNING MsgRouterThr:15796 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-14 15:13:12,689 INFO    MainThread:15796 [wandb_run.py:_restore():1752] restore
2022-03-14 15:13:12,736 INFO    SenderThread:15796 [sender.py:finish():1070] shutting down sender
2022-03-14 15:13:12,736 INFO    WriterThread:15796 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\run-2w3zwz8t.wandb
2022-03-14 15:13:12,736 INFO    SenderThread:15796 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-14 15:13:13,469 INFO    SenderThread:15796 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\output.log
2022-03-14 15:13:13,470 INFO    SenderThread:15796 [dir_watcher.py:finish():313] scan: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files
2022-03-14 15:13:13,470 INFO    SenderThread:15796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\conda-environment.yaml conda-environment.yaml
2022-03-14 15:13:13,470 INFO    SenderThread:15796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\config.yaml config.yaml
2022-03-14 15:13:13,471 INFO    SenderThread:15796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\output.log output.log
2022-03-14 15:13:13,477 INFO    SenderThread:15796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\requirements.txt requirements.txt
2022-03-14 15:13:13,478 INFO    SenderThread:15796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\wandb-metadata.json wandb-metadata.json
2022-03-14 15:13:13,540 INFO    SenderThread:15796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\wandb-summary.json wandb-summary.json
2022-03-14 15:13:13,551 INFO    SenderThread:15796 [file_pusher.py:finish():177] shutting down file pusher
2022-03-14 15:13:13,551 INFO    SenderThread:15796 [file_pusher.py:join():182] waiting for file pusher
2022-03-14 15:13:14,610 INFO    Thread-32 :15796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\requirements.txt
2022-03-14 15:13:14,643 INFO    Thread-31 :15796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\output.log
2022-03-14 15:13:14,643 INFO    Thread-33 :15796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\wandb-summary.json
2022-03-14 15:13:14,648 INFO    Thread-30 :15796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\config.yaml
2022-03-14 15:13:14,692 INFO    Thread-29 :15796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151305-2w3zwz8t\files\conda-environment.yaml
2022-03-14 15:13:15,398 ERROR   BackendThr:15796 [internal.py:wandb_internal():158] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 99, in _run
    record = self._input_record_q.get(timeout=1)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
2022-03-14 15:13:18,324 INFO    MainThread:15796 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-03-14 15:13:18,435 INFO    MainThread:15796 [wandb_run.py:_restore():1752] restore
2022-03-14 15:13:18,461 INFO    MainThread:15796 [internal.py:handle_exit():77] Internal process exited
