2022-03-14 22:54:28,413 INFO    MainThread:16280 [wandb_setup.py:_flush():71] setting env: {'start_method': 'thread'}
2022-03-14 22:54:28,413 INFO    MainThread:16280 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-14 22:54:28,413 INFO    MainThread:16280 [wandb_init.py:_log_setup():371] Logging user logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\logs\debug.log
2022-03-14 22:54:28,413 INFO    MainThread:16280 [wandb_init.py:_log_setup():372] Logging internal logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\logs\debug-internal.log
2022-03-14 22:54:28,414 INFO    MainThread:16280 [wandb_init.py:init():404] calling init triggers
2022-03-14 22:54:28,428 INFO    MainThread:16280 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'workers': 20, 'epochs': 2, 'batch_size': 64, 'learning_rate': 0.2, 'dropout': 0.01, 'weight_decay': 1e-06, 'clip': 1, 'betas': (0.9, 0.98), 'eps': 1e-09, 'loss_fn': 'cross_entropy', 'dmodel': 768, 'nhead': 3, 'dfeedforward': 256, 'nlayers': 3, 'tokenizer': 'bert-base-multilingual-cased', 'mbert_out_size': 768, 'checkpoint_dir': WindowsPath('checkpoint'), 'ngpus_per_node': 1, 'rank': 0, 'dist_url': 'tcp://localhost:58472', 'world_size': 1}
2022-03-14 22:54:28,429 INFO    MainThread:16280 [wandb_init.py:init():460] starting backend
2022-03-14 22:54:28,435 INFO    MainThread:16280 [backend.py:ensure_launched():216] starting backend process...
2022-03-14 22:54:28,436 INFO    MainThread:16280 [backend.py:ensure_launched():222] started backend process with pid: 0
2022-03-14 22:54:28,436 INFO    BackendThr:16280 [internal.py:wandb_internal():90] W&B internal server running at pid: 16280, started at: 2022-03-14 22:54:28.436399
2022-03-14 22:54:28,437 INFO    MainThread:16280 [wandb_init.py:init():469] backend started and connected
2022-03-14 22:54:28,439 INFO    MainThread:16280 [wandb_init.py:init():533] updated telemetry
2022-03-14 22:54:28,441 INFO    WriterThread:16280 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\run-1tbngd49.wandb
2022-03-14 22:54:28,488 INFO    MainThread:16280 [wandb_init.py:init():563] communicating current version
2022-03-14 22:54:28,623 INFO    MainThread:16280 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-14 22:54:28,624 INFO    MainThread:16280 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-14 22:54:28,993 INFO    MainThread:16280 [wandb_init.py:init():606] starting run threads in backend
2022-03-14 22:54:28,998 INFO    SenderThread:16280 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files
2022-03-14 22:54:28,998 INFO    SenderThread:16280 [sender.py:_start_run_threads():807] run started: 1tbngd49 with start time 1647278668
2022-03-14 22:54:28,999 INFO    SenderThread:16280 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-14 22:54:29,997 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\requirements.txt
2022-03-14 22:54:29,998 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\conda-environment.yaml
2022-03-14 22:54:29,998 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-summary.json
2022-03-14 22:54:31,351 INFO    SenderThread:16280 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-14 22:54:31,369 INFO    MainThread:16280 [wandb_run.py:_console_start():1810] atexit reg
2022-03-14 22:54:31,371 INFO    MainThread:16280 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-14 22:54:31,371 INFO    MainThread:16280 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-14 22:54:31,373 INFO    MainThread:16280 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-14 22:54:31,373 INFO    MainThread:16280 [wandb_init.py:init():633] run started, returning control to user process
2022-03-14 22:54:32,006 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\conda-environment.yaml
2022-03-14 22:54:32,006 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-metadata.json
2022-03-14 22:54:32,007 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:54:32,313 INFO    Thread-22 :16280 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmp2rptoqwawandb\tm2ki4ub-wandb-metadata.json
2022-03-14 22:54:34,034 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:54:36,047 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:59:43,777 WARNING MsgRouterThr:16280 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-14 22:59:43,934 INFO    MainThread:16280 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-14 22:59:43,935 INFO    MainThread:16280 [wandb_run.py:_restore():1752] restore
2022-03-14 22:59:44,244 INFO    SenderThread:16280 [sender.py:finish():1070] shutting down sender
2022-03-14 22:59:44,244 INFO    SenderThread:16280 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-14 22:59:44,277 INFO    SenderThread:16280 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:59:44,277 INFO    SenderThread:16280 [dir_watcher.py:finish():313] scan: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files
2022-03-14 22:59:44,278 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\conda-environment.yaml conda-environment.yaml
2022-03-14 22:59:44,278 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\config.yaml config.yaml
2022-03-14 22:59:44,279 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log output.log
2022-03-14 22:59:44,288 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\requirements.txt requirements.txt
2022-03-14 22:59:44,290 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-metadata.json wandb-metadata.json
2022-03-14 22:59:44,296 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-summary.json wandb-summary.json
2022-03-14 22:59:44,301 INFO    SenderThread:16280 [file_pusher.py:finish():177] shutting down file pusher
2022-03-14 22:59:44,302 INFO    SenderThread:16280 [file_pusher.py:join():182] waiting for file pusher
2022-03-14 22:59:44,605 INFO    WriterThread:16280 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\run-1tbngd49.wandb
2022-03-14 22:59:45,252 INFO    Thread-33 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\requirements.txt
2022-03-14 22:59:45,259 INFO    Thread-30 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\conda-environment.yaml
2022-03-14 22:59:45,265 INFO    Thread-34 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-summary.json
2022-03-14 22:59:45,285 INFO    Thread-32 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:59:45,296 INFO    Thread-31 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\config.yaml
2022-03-14 22:59:46,140 ERROR   BackendThr:16280 [internal.py:wandb_internal():158] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 99, in _run
    record = self._input_record_q.get(timeout=1)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
2022-03-14 22:59:48,975 INFO    MainThread:16280 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-03-14 22:59:49,082 INFO    MainThread:16280 [wandb_run.py:_restore():1752] restore
2022-03-14 22:59:49,107 INFO    MainThread:16280 [internal.py:handle_exit():77] Internal process exited
